name: bank123
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get: ^4.6.5
  dio: ^5.3.3
  local_auth: ^2.3.0
  path: ^1.9.0
  shared_preferences: ^2.5.3
  http: ^1.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  uuid: ^4.5.2
  jwt_decoder: ^2.0.1
  firebase_crashlytics: ^4.3.10
  crypto: ^3.0.7
  safe_device: ^1.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#795548" # Colors.brown
  image: "assets/icon/bank_icon_padded.png"
  android_12:
    image: "assets/icon/bank_icon_padded.png"
    color: "#795548"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/bank_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#795548" # Colors.brown

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

