name: bank123
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get: ^4.6.5
  dio: ^5.3.3
  local_auth: ^2.3.0
  path: ^1.9.0
  shared_preferences: ^2.5.3
  http: ^1.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  uuid: ^4.5.2
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
